version: '3.4'

volumes:
  poptape_lister:
    name: poptape_lister

services:
  api:
    env_file: app/.env
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/lister/api:v0.1
    ports:
      - "1500:8400"
    restart: always
    depends_on:
      - mongodb
    volumes:
      - /var/log:${LOGFILE}
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - net_poptape 
  mongodb:
    image: mongo
    restart: always
    ports:
      - "1501:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes: 
      - poptape_lister:/data/db
    networks:
      - net_poptape    

networks:
  net_poptape:
    external: true
