version: '3'
services:
  api:
    env_file: app/.env
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/lister/api:v0.1
    ports:
      - 1500:8400
    restart: always
    depends_on:
      - mongo_db
    volumes:
      - /var/log:${LOGFILE}
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - net_poptape 
  mongo_db:
    image: mongo:3.6
    restart: always
    env_file: app/.env
    ports:
      - 1501:27017
    volumes: 
      - poptape_lister:/data/db
    networks:
      - net_poptape    

networks:
  net_poptape:
    external: true

volumes:
  poptape_lister:
